<?php
$this->headTitle('Aula');

$form = $this->form;

$titulo = $form->get('titulo')->setAttributes([
    'class'=>'form-control',

])->setLabelAttributes(['class' => 'control-label']);

$id = $form->get('id')->setAttributes([
    'class'=>'form-control',
]);

$tipo = $form->get('tipo')->setAttributes([
    'class'=>'form-control',
])->setLabelAttributes(['class' => 'control-label']);

$file = $form->get('file')->setAttributes([
    'class'=>'form-control',
])->setLabelAttributes(['class' => 'control-label']);



$status = $form->get('status')->setAttributes([
    'class'=>'form-control',
])->setLabelAttributes(['class' => 'control-label']);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->get('submit')->setValue('Salvar');


$dados = $this->dataBase;

?>


<!-- page content -->
<div class="right_col" role="main">
    <div class="">

        <div class="page-title">
            <div class="title_left">
                <h3>Aula</h3>

                <div class="clearfix"></div>
                <p>
                    <a class="btn btn-default" href="
    <?= $this->url('admin/default', ['controller' => 'aula', 'action'=>'new']); ?>">
                        <i class="fa fa-plus-circle"></i> Novo
                    </a>

                    <a class="btn btn-default" href="
    <?= $this->url('admin/default', ['controller' => 'aula']); ?>">
                        <i class="fa fa-navicon"></i> Listar
                    </a>
                </p>

            </div>

        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-9 col-sm-9 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Editar</h2>

                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <?php

                        $flash = $this->flashMessenger();
                        $flash->setMessageOpenFormat('<div%s>
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                                    &times;
                                </button>
                                <ul><li>')
                            ->setMessageSeparatorString('</li><li>')
                            ->setMessageCloseString('</li></ul></div>');

                        echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
                        echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
                        echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
                        echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));

                        ?>

                        <br />

                        <?= $this->form()->openTag($form); ?>

                        <?= $this->formHidden($form->get('id'));?>


                        <?php $message = $this->formElementErrors($titulo, ['class' => 'help-block']); ?>
                        <div class="form-group<?= $message ? " has-error" : "" ?>">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Titulo <span class="required">*</span>
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">

                                <?= $this->formElement($titulo); ?>
                                <?= $message ?>

                            </div>
                        </div>

                

                         <?php $message = $this->formElementErrors($tipo, ['class' => 'help-block']); ?>
                        <div class="form-group<?= $message ? " has-error" : "" ?>">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Tipo <span class="required">*</span>
                            </label>
                            <div class="col-md-3 col-sm-3 col-xs-12">

                                <?= $this->formElement($tipo); ?>
                                <?= $message ?>

                            </div>
                        </div>

                        <?php $message = $this->formElementErrors($file, ['class' => 'help-block']); ?>
                        <div class="form-group<?= $message ? " has-error" : "" ?>">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Arquivo
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">
                                <?= $this->formElement($file); ?>
                                <?= $message ?>
                            </div>
                        </div>



                        <?php $message = $this->formElementErrors($status, ['class' => 'help-block']); ?>
                        <div class="form-group<?= $message ? " has-error" : "" ?>">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Status <span class="required">*</span>
                            </label>
                            <div class="col-md-2 col-sm-2 col-xs-12">

                                <?= $this->formElement($status); ?>
                                <?= $message ?>

                            </div>
                        </div>

                    </div>
                </div>
            </div>

            <div class="col-md-3 col-xs-12">

                <div class="x_panel">
                    <div class="x_title">
                        <h2>Complementos</h2>

                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <a href="javascript:void(0);" onclick="openModalVideo()" class="btn btn-app">
                            <span class="badge bg-green"></span>
                            <i class="fa fa-play"></i> Video
                        </a>
                        <a href="javascript:void(0);" onclick="openModalAtividade()" class="btn btn-app">
                            <span class="badge bg-orange"></span>
                            <i class="fa fa-edit"></i> Atividade
                        </a>

                        <a href="javascript:void(0);" onclick="openModalMaterial()"  class="btn btn-app">
                            <span class="badge bg-blue"></span>
                            <i class="fa fa-files-o"></i> Material
                        </a>

                        <a href="javascript:void(0);" onclick="openModalLink()" class="btn btn-app">
                            <span class="badge bg-orange"></span>
                            <i class="fa fa-link"></i> Links
                        </a>

                    </div>



                </div>

                <div class="x_panel">
                    <div class="x_content">
                        <br />
                        <div class="dashboard-widget-content file">

                            <?php
                            $file = $dados->getFile();
                            if(empty($file)) {
                            }else {

                                ?>


                                        <a class="btn btn-primary" style="width: 100%" href="http://<?php echo $_SERVER['HTTP_HOST']; ?>/baixar.php?c=material&f=<?php echo $dados->getFile(); ?>">
                                        <i class="fa fa-download"></i> Arquivo
                                      </a>

                                <?php
                            }
                            ?>

                        </div>
                    </div>
                </div>



            </div>
            <div class="clearfix"></div>



            <!--videos-->
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Vídeos</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                    </li>
                                    <li>
                                    </li>
                                </ul>
                            </li>

                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <ul class="to_do">

                            <?php
                            $resVideos = $this->resVideos;

                            //listo todos videos do cronograma
                            foreach ($this->videoAnexado as $videos) {

                                //busco todos videos iguais o cronograma
                                foreach($resVideos as $resVid){

                                    if($videos->getAnexo() == $resVid->getId()){
                                        ?>

                                        <li>
                                            <div class="row">
                                                <div class="col-md-9 col-sm-9 col-xs-12">

                                                    <?php echo $resVid->getTitulo().' - '?><a title="Assistir" href="<?php echo $this->url('admin/default',
                                                        array('controller'=>'videos','action'=>'edit','id'=>$resVid->getId()));?>"><i class="fa fa-eye"></i></a>
                                                </div>
                                                <div class="col-md-3 col-sm-3 col-xs-12">
                                                    <a class="deletarItem pull-right" id="<?php echo $videos->getId(); ?>" controller="anexo" href="javascript:void(0);"><i class="fa fa-times"></i></a>
                                                </div>
                                            </div>
                                        </li>
                                        
                                        <?php
                                    }
                                }
                            }
                            ?>


                        </ul>

                    </div>
                </div>
            </div>
            <!--end videos-->

            <!--atividades-->
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Atividades</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                    </li>
                                    <li>
                                    </li>
                                </ul>
                            </li>

                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <div class="">
                            <ul class="to_do">

                                <?php

                                //listo todos videos do cronograma
                                foreach ($this->resAtividadeAnexado as $atividade) {
                                    //busco todos videos iguais o cronograma
                                    foreach($this->resAtividades as $resAtividade){

                                        if($atividade->getAnexo() == $resAtividade->getId()){
                                            ?>
                                            <li>
                                                <div class="row">
                                                    <div class="col-md-9 col-sm-9 col-xs-12">

                                                        <?php echo $resAtividade->getTitulo().' - '?><a title="Assistir" href="javascript:void(0);"><i class="fa fa-eye"></i></a>
                                                    </div>
                                                    <div class="col-md-3 col-sm-3 col-xs-12">
                                                        <a class="deletarItem pull-right" id="<?php echo $atividade->getId(); ?>" controller="anexo" href="javascript:void(0);"><i class="fa fa-times"></i></a>
                                                    </div>
                                                </div>
                                            </li>
                                            <?php
                                        }else{
                                        }
                                    }
                                }
                                ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!--end atividadades-->
            <div class="clearfix"></div>

            <!-- material-->
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Material</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                    </li>
                                    <li>
                                    </li>
                                </ul>
                            </li>
                            <li><a href="#" class="dropdown-toggle push-right" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                </a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <div class="">
                            <ul class="to_do">
                                <?php
                                foreach($this->resMaterialAnexado as $material) {
                                    //busco todos videos iguais o cronograma
                                    foreach($this->resMaterial as $resMaterial){

                                        if($material->getAnexo() == $resMaterial->getId()){

                                            ?>

                                            <li>
                                                <div class="row">
                                                    <div class="col-md-9 col-sm-9 col-xs-12">

                                                        <?php echo $resMaterial->getTitulo().' - '?><a title="Baixar Arquivo" href="http://<?php echo $_SERVER['HTTP_HOST']; ?>/baixar.php?c=material&f=<?php echo $resMaterial->getFile(); ?>"><i class="fa fa-download"></i></a>
                                                    </div>
                                                    <div class="col-md-3 col-sm-3 col-xs-12">
                                                        <a class="deletarItem pull-right" id="<?php echo $material->getId(); ?>" controller="anexo" href="javascript:void(0);"><i class="fa fa-times"></i></a>
                                                    </div>
                                                </div>
                                            </li>
                                            <?php
                                        }else {

                                        }
                                    }
                                }
                                ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!--end material-->

            <!--links -->
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Links</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                    </li>
                                    <li>
                                    </li>
                                </ul>
                            </li>
                            <li><a href="#" class="dropdown-toggle push-right" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                </a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <div class="">
                            <ul class="to_do">

                                <?php

                                foreach ($this->resLinkAnexado as $link) {
                                    //busco todos videos iguais o cronograma
                                    foreach($this->resLink as $resLink){

                                        if($link->getAnexo() == $resLink->getId()){

                                            ?>

                                            <li>
                                                <div class="row">
                                                    <div class="col-md-9 col-sm-9 col-xs-12">
                                                        <a target="_blank" href="<?php echo $resLink->getUrl(); ?>"> <?php echo $resLink->getUrl(); ?></a>
                                                    </div>
                                                    <div class="col-md-3 col-sm-3 col-xs-12">
                                                        <a class="deletarItem pull-right" id="<?php echo $link->getId(); ?>" controller="anexo" href="javascript:void(0);"><i class="fa fa-times"></i></a>
                                                    </div>
                                                </div>
                                            </li>
                                            <?php
                                        }
                                    }
                                }
                                ?>

                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end links-->




            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">

                    <div class="x_content">
                        <?= $this->formElement($form->get('texto')); ?>
                        <?= $this->formElementErrors($form->get('texto')); ?>

                        <br />

                        <div class="ln_solid"></div>

                        <div class="form-group">

                            <div class="col-xs-12">

                                <a href="<?php echo $this->url('admin/default', ['controller' => 'aula']) ?>"  class="btn btn-danger"><span class="glyphicon glyphicon-remove-sign"></span> Cancelar</a>

                                <?= $this->formElement($form->get('submit')); ?>
                            </div>

                        </div>

                    </div>
                </div>
            </div>

            <?php  echo $this->form()->closeTag(); ?>

        </div>

        <!--img destaque-->

        <!--end img destaque-->




    </div>
</div>
<!-- /page content -->

<script>
    function openModalVideo(){
        $('.video').modal();
    }

    function openModalAtividade(){
        $('.atividades').modal();
    }

    function openModalMaterial(){
        $('.material').modal();
    }

    function openModalLink(){
        $('.link').modal();
    }
</script>

<!--video-->
<div class="modal fade video" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Vídeos</h4>
            </div>
            <div class="modal-body">
                <!--conteudo video-->
                
                            <!--listar videos-->

                            <table id="datatable-video" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                                <thead>
                                <tr>
                                    <th>Cod</th>
                                    <th>Titulo</th>
                                    <th>Tipo</th>
                                    <th>Ação</th>
                                </tr>
                                </thead>
                                <tbody>

                                <?php
                                foreach ($this->resVideos as $vid){


                                ?>
                                <tr>
                                    <td><?= $vid->getId(); ?></td>
                                    <td><?= $vid->getTitulo(); ?></td>
                                    <td><?= $vid->getTipo(); ?></td>
                                    <td>

                                        <a class="btn btn-xs btn-primary tab3" href="#tab_content3" role="tab" id="profile-tab2" data-toggle="tab" aria-expanded="false"><i class="glyphicon glyphicon-edit"></i></a>

                                        <a class="btn btn-xs btn-primary anexarItem" rota="anexo" data-controller="Video" data-aula="<?php echo  $dataBase->getId();  ?>" data-anexo="<?php echo $vid->getId(); ?>" href="javascript:void(0);" ><i class="fa fa-share"></i> Anexar</a>

                                    </td>

                                </tr>

                                <?php } ?>

                                </tbody>
                            </table>
                            <!--end listar-->
                <!--end conteudo-->
               </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Fechar</button>

            </div>

        </div>
    </div>
</div>
<!--end video-->

<!--atividade-->
<div class="modal fade atividades" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Atividade</h4>
            </div>
            <div class="modal-body">
                <!--conteudo video-->

                 <!--listar atividades-->

                <table id="datatable-atividade" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th>Cod</th>
                        <th>Titulo</th>
                        <th>Tipo</th>
                        <th>Ação</th>
                    </tr>
                    </thead>
                    <tbody>

                    <?php
                    foreach ($this->resAtividades as $ativid){


                        ?>
                        <tr>
                            <td><?= $ativid->getId(); ?></td>
                            <td><?= $ativid->getTitulo(); ?></td>
                            <td><?= $ativid->getTipo(); ?></td>
                            <td>

                                <a class="btn btn-xs btn-primary tab3" href="#tab_content3" role="tab" id="profile-tab2" data-toggle="tab" aria-expanded="false"><i class="glyphicon glyphicon-edit"></i></a>

                                <a class="btn btn-xs btn-primary anexarItem" rota="anexo" data-controller="Atividade" data-aula="<?php echo  $dataBase->getId();  ?>" data-anexo="<?php echo $ativid->getId(); ?>" href="javascript:void(0);" ><i class="fa fa-share"></i> Anexar</a>

                            </td>

                        </tr>

                    <?php } ?>

                    </tbody>
                </table>
                <!--end listar-->

                <!--end conteudo-->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Fechar</button>

            </div>

        </div>
    </div>
</div>
<!--end atividade-->

<!--material-->
<div class="modal fade material" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Material</h4>
            </div>
            <div class="modal-body">
                <!--conteudo video-->

                <!--listar material-->

                <table id="datatable-material" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th>Cod</th>
                        <th>Titulo</th>
                        <th>Tipo</th>
                        <th>Ação</th>
                    </tr>
                    </thead>
                    <tbody>

                    <?php
                    foreach ($this->resMaterial as $mat){

                        ?>
                        <tr>
                            <td><?= $mat->getId(); ?></td>
                            <td><?= $mat->getTitulo(); ?></td>
                            <td><?= $mat->getTipo(); ?></td>
                            <td>

                                <a class="btn btn-xs btn-primary tab3" href="#tab_content3" role="tab" id="profile-tab2" data-toggle="tab" aria-expanded="false"><i class="glyphicon glyphicon-edit"></i></a>

                                <a class="btn btn-xs btn-primary anexarItem" rota="anexo" data-controller="Material" data-aula="<?php echo  $dataBase->getId();  ?>" data-anexo="<?php echo $mat->getId(); ?>" href="javascript:void(0);" ><i class="fa fa-share"></i> Anexar</a>

                            </td>

                        </tr>

                    <?php } ?>

                    </tbody>
                </table>




                <!--end listar-->

                <!--end conteudo-->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Fechar</button>

            </div>

        </div>
    </div>
</div>
<!--end atividade-->

<!--link-->
<div class="modal fade link" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Link</h4>
            </div>
            <div class="modal-body">
                <!--conteudo video-->

                <!--listar material-->

                <table id="datatable-link" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th>Cod</th>
                        <th>Titulo</th>
                        <th>Ação</th>
                    </tr>
                    </thead>
                    <tbody>

                    <?php
                    foreach ($this->resLink as $link){

                        ?>
                        <tr>
                            <td><?= $link->getId(); ?></td>
                            <td><?= $link->getTitulo(); ?></td>
                            <td>

                                <a class="btn btn-xs btn-primary tab3" href="#tab_content3" role="tab" id="profile-tab2" data-toggle="tab" aria-expanded="false"><i class="glyphicon glyphicon-edit"></i></a>

                                <a class="btn btn-xs btn-primary anexarItem" rota="anexo" data-controller="Link" data-aula="<?php echo  $dataBase->getId();  ?>" data-anexo="<?php echo $link->getId(); ?>" href="javascript:void(0);" ><i class="fa fa-share"></i> Anexar</a>

                            </td>

                        </tr>

                    <?php } ?>

                    </tbody>
                </table>
                <!--end listar-->

                <!--end conteudo-->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Fechar</button>

            </div>

        </div>
    </div>
</div>
<!--end link-->

<script>
    function openModal(){
        $('.video').modal();
    }

    function openModalAtividade(){
        $('.atividades').modal();
    }

    function openModalMaterial(){
        $('.material').modal();
    }

    function openModalLink(){
        $('.link').modal();
    }


</script>
