<?php
$this->headTitle('Aula');

$form = $this->form;

$titulo = $form->get('titulo')->setAttributes([
    'class'=>'form-control',
    'readonly' => 'readonly',

])->setLabelAttributes(['class' => 'control-label', ]);


$tipo = $form->get('tipo')->setAttributes([
    'class'=>'form-control',
    'readonly' => 'readonly'
])->setLabelAttributes(['class' => 'control-label']);


$status = $form->get('status')->setAttributes([
    'class'=>'form-control',
    'readonly' => 'readonly'
])->setLabelAttributes(['class' => 'control-label']);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);



$dados = $this->dataBase;

?>


<!-- page content -->
<div class="right_col" role="main">
    <div class="">

        <div class="page-title">
            <div class="title_left"  style="width:100%;">
                <h3>Aula</h3>

                <div class="clearfix"></div>

                <div class="row">
                    <div class="col-sm-11">
                        <p>

                            <a class="btn btn-default" href="
    <?= $this->url('admin/default', ['controller' => 'aula']); ?>">
                                <i class="fa fa-navicon"></i> Listar
                            </a>
                        </p>
                    </div>

                    <div class="col-sm-1">

                        <a class="btn btn-primary pull-right" href="javascript:history.back()">
                            <i class="fa fa-reply"></i> Voltar
                        </a>
                    </div>
                </div>



            </div>

        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-9 col-sm-9 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Visualizar</h2>

                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">


                        <?= $this->form()->openTag($form); ?>





                        <div class="form-group">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Titulo
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">

                                <?= $this->formElement($titulo); ?>


                            </div>
                        </div>

                


                        <div class="form-group">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Tipo
                            </label>
                            <div class="col-md-3 col-sm-3 col-xs-12">

                                <?= $this->formElement($tipo); ?>


                            </div>
                        </div>





                        <div class="form-group">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Status
                            </label>
                            <div class="col-md-2 col-sm-2 col-xs-12">

                                <?= $this->formElement($status); ?>


                            </div>
                        </div>

                    </div>
                </div>
            </div>

            <div class="col-md-3 col-xs-12">

                <div class="x_panel">
                    <div class="x_title">
                        <h2>Complementos</h2>

                        <div class="clearfix"></div>
                    </div>

                </div>

                <div class="x_panel">
                    <div class="x_content">
                        <br />
                        <div class="dashboard-widget-content file">

                            <?php
                            $file = $dados->getFile();
                            if(empty($file)) {
                            }else {

                                ?>


                                        <a class="btn btn-primary" style="width: 100%" href="http://<?php echo $_SERVER['HTTP_HOST']; ?>/baixar.php?c=material&f=<?php echo $dados->getFile(); ?>">
                                        <i class="fa fa-download"></i> Arquivo
                                      </a>

                                <?php
                            }
                            ?>

                        </div>
                    </div>
                </div>



            </div>
            <div class="clearfix"></div>



            <!--videos-->
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Vídeos</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <ul class="to_do">

                            <?php
                            $resVideos = $this->resVideos;

                            //listo todos videos do cronograma
                            foreach ($this->videoAnexado as $videos) {

                                //busco todos videos iguais o cronograma
                                foreach($resVideos as $resVid){

                                    if($videos->getAnexo() == $resVid->getId()){
                                        ?>

                                        <li>
                                            <div class="row">
                                                <div class="col-md-9 col-sm-9 col-xs-12">

                                                    <?php echo $resVid->getTitulo().' - '?>
                                                    <a title="Assistir" href="javascript:void(0);" onclick="openModalVideo_<?php echo $resVid->getId(); ?>()" ><i class="fa fa-eye"></i></a>




                                                </div>
                                                <div class="col-md-3 col-sm-3 col-xs-12">

                                                </div>
                                            </div>
                                        </li>


                                        <!--modal video-->
                                        <div class="modal fade video_<?php echo $resVid->getId(); ?>" tabindex="-1" role="dialog" aria-hidden="true">
                                            <div class="modal-dialog modal-lg">
                                                <div class="modal-content">

                                                    <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                                                        </button>
                                                        <h4 class="modal-title" id="myModalLabel">Vídeo</h4>
                                                    </div>
                                                    <div class="modal-body">
                                                        <!--conteudo video-->

                                                        <div class="box-body">

                                                            <?php
                                                            if ($resVid->getTipo() == 'YouTube') {

                                                                $youtube = explode('=', $resVid->getLink());

                                                                echo '<iframe width="100%" height="300" src="https://www.youtube.com/embed/' . $youtube[1] . '" frameborder="0" allowfullscreen></iframe>';


                                                            } elseif ($resVid->getTipo() == 'Vimeo') {

                                                                $vimeo = explode('/', $dados->getLink());

                                                                echo '<iframe src="https://player.vimeo.com/video/' . $vimeo[3] . '?title=0&byline=0&portrait=0" width="100%" height="300" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>';

                                                            } else {

                                                                ?>

                                                                <video id="example_video_1" class="video-js vjs-default-skin" controls preload="none" width="100%" height="300" poster="<?php echo $this->basePath() . '/img/player_live.jpg'; ?>" data-setup="{}">
                                                                    <source src="<?php echo $this->basePath() . '/video/' . $resVid->getFile(); ?>" type="video/mp4">

                                                                    <!-- Tracks need an ending tag thanks to IE9 -->
                                                                    <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
                                                                </video>

                                                                <?php

                                                            };


                                                            ?>


                                                        </div><!-- /.box-body -->



                                                        <!--end conteudo-->
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-primary" data-dismiss="modal">Fechar</button>

                                                    </div>

                                                </div>
                                            </div>
                                        </div>
                                        <!--end video-->


                                        <script>
                                            function openModalVideo_<?php echo $resVid->getId(); ?>(){
                                                $('.video_<?php echo $resVid->getId(); ?>').modal();
                                            }
                                        </script>






                                        
                                        <?php
                                    }
                                }
                            }
                            ?>


                        </ul>

                    </div>
                </div>
            </div>
            <!--end videos-->

            <!--atividades-->
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Atividades</h2>

                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <div class="">
                            <ul class="to_do">

                                <?php

                                /** @var \User\Entity\Anexo $atividade */
                                //listo todos videos do cronograma
                                foreach ($this->resAtividadeAnexado as $atividade) {
                                    //busco todos videos iguais o cronograma



                                        /** @var \User\Entity\Atividade $resAtividade */
                                    foreach($this->resAtividades as $resAtividade){

                                        if($atividade->getAnexo() == $resAtividade->getId()){
                                            ?>
                                            <li>
                                                <div class="row">
                                                    <div class="col-md-9 col-sm-9 col-xs-12">

                                                        <?php echo $resAtividade->getTitulo().' - '?><a title="Baixar Arquivo" href="http://<?php echo $_SERVER['HTTP_HOST']; ?>/baixar.php?c=atividade&f=<?php echo $resAtividade->getFile(); ?>"><i class="fa fa-download"></i></a>
                                                    </div>
                                                    <div class="col-md-3 col-sm-3 col-xs-12">


                                                    </div>
                                                </div>
                                            </li>
                                            <?php
                                        }else{
                                        }
                                    }
                                }
                                ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!--end atividadades-->
            <div class="clearfix"></div>

            <!-- material-->
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Material</h2>

                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <div class="">
                            <ul class="to_do">
                                <?php
                                foreach($this->resMaterialAnexado as $material) {
                                    //busco todos videos iguais o cronograma
                                    foreach($this->resMaterial as $resMaterial){

                                        if($material->getAnexo() == $resMaterial->getId()){

                                            ?>

                                            <li>
                                                <div class="row">
                                                    <div class="col-md-9 col-sm-9 col-xs-12">

                                                        <?php echo $resMaterial->getTitulo().' - '?><a title="Baixar Arquivo" href="http://<?php echo $_SERVER['HTTP_HOST']; ?>/baixar.php?c=material&f=<?php echo $resMaterial->getFile(); ?>"><i class="fa fa-download"></i></a>
                                                    </div>
                                                    <div class="col-md-3 col-sm-3 col-xs-12">

                                                    </div>
                                                </div>
                                            </li>
                                            <?php
                                        }else {

                                        }
                                    }
                                }
                                ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!--end material-->

            <!--links -->
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Links</h2>

                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <div class="">
                            <ul class="to_do">

                                <?php

                                foreach ($this->resLinkAnexado as $link) {
                                    //busco todos videos iguais o cronograma
                                    foreach($this->resLink as $resLink){

                                        if($link->getAnexo() == $resLink->getId()){

                                            ?>

                                            <li>
                                                <div class="row">
                                                    <div class="col-md-9 col-sm-9 col-xs-12">
                                                        <a target="_blank" href="<?php echo $resLink->getUrl(); ?>"> <?php echo $resLink->getUrl(); ?></a>
                                                    </div>
                                                    <div class="col-md-3 col-sm-3 col-xs-12">

                                                    </div>
                                                </div>
                                            </li>
                                            <?php
                                        }
                                    }
                                }
                                ?>

                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end links-->




            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">

                    <div class="x_content">
                        <?php

                        $texto = $dados->getTexto();
                        if(empty($texto)) {
                        }else {

                            echo $texto;
                        }

                        ?>

                        <br />

                        <div class="ln_solid"></div>

                        <div class="form-group">

                            <div class="col-xs-12">

                                <a href="<?php echo $this->url('admin/default', ['controller' => 'aula']) ?>"  class="btn btn-danger"><span class="glyphicon glyphicon-remove-sign"></span> voltar</a>


                            </div>

                        </div>

                    </div>
                </div>
            </div>

            <?php  echo $this->form()->closeTag(); ?>

        </div>

        <!--img destaque-->

        <!--end img destaque-->




    </div>
</div>
<!-- /page content -->

