<?php

namespace DoctrineORMModule\Proxy\__CG__\User\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \User\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'isteacher', '' . "\0" . 'User\\Entity\\User' . "\0" . 'role', '' . "\0" . 'User\\Entity\\User' . "\0" . 'codigo', 'email', 'fullName', 'profissao', 'contrato', 'boleto', 'cronograma', 'password', 'status', '' . "\0" . 'User\\Entity\\User' . "\0" . 'salt', 'dateCreated', 'dateUpdated', 'passwordResetToken', 'passwordResetTokenCreationDate', 'activationKey', 'file', 'thumb', 'cpf', 'rua', 'numero', 'bairro', 'complemento', 'cidade', 'estado', 'cep', 'rg', 'celular', 'celular2', 'telefone', '' . "\0" . 'User\\Entity\\User' . "\0" . 'polo', 'sexo', 'pai', 'mae', 'naturalidade', '' . "\0" . 'User\\Entity\\User' . "\0" . 'nascimento', 'emissor', 'recado', 'formacao', 'empresa', 'empresaendereco', 'empresanumero', 'empresacomplemento', 'empresabairro', 'empresacidade', 'empresaestado', 'empresacep', 'empresatel', 'empresaramal', 'empresacel', 'website', 'empresaemail'];
        }

        return ['__isInitialized__', 'id', 'isteacher', '' . "\0" . 'User\\Entity\\User' . "\0" . 'role', '' . "\0" . 'User\\Entity\\User' . "\0" . 'codigo', 'email', 'fullName', 'profissao', 'contrato', 'boleto', 'cronograma', 'password', 'status', '' . "\0" . 'User\\Entity\\User' . "\0" . 'salt', 'dateCreated', 'dateUpdated', 'passwordResetToken', 'passwordResetTokenCreationDate', 'activationKey', 'file', 'thumb', 'cpf', 'rua', 'numero', 'bairro', 'complemento', 'cidade', 'estado', 'cep', 'rg', 'celular', 'celular2', 'telefone', '' . "\0" . 'User\\Entity\\User' . "\0" . 'polo', 'sexo', 'pai', 'mae', 'naturalidade', '' . "\0" . 'User\\Entity\\User' . "\0" . 'nascimento', 'emissor', 'recado', 'formacao', 'empresa', 'empresaendereco', 'empresanumero', 'empresacomplemento', 'empresabairro', 'empresacidade', 'empresaestado', 'empresacep', 'empresatel', 'empresaramal', 'empresacel', 'website', 'empresaemail'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getRole()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRole', []);

        return parent::getRole();
    }

    /**
     * {@inheritDoc}
     */
    public function setRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRole', [$role]);

        return parent::setRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getContrato()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContrato', []);

        return parent::getContrato();
    }

    /**
     * {@inheritDoc}
     */
    public function setContrato($contrato)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContrato', [$contrato]);

        return parent::setContrato($contrato);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsteacher()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsteacher', []);

        return parent::getIsteacher();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsteacher($isteacher)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsteacher', [$isteacher]);

        return parent::setIsteacher($isteacher);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigo', []);

        return parent::getCodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigo($codigo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigo', [$codigo]);

        return parent::setCodigo($codigo);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getFullName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFullName', []);

        return parent::getFullName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFullName($fullName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFullName', [$fullName]);

        return parent::setFullName($fullName);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfissao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfissao', []);

        return parent::getProfissao();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfissao($profissao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfissao', [$profissao]);

        return parent::setProfissao($profissao);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalt($salt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalt', [$salt]);

        return parent::setSalt($salt);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusAsString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusAsString', []);

        return parent::getStatusAsString();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreated', []);

        return parent::getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreated', []);

        return parent::setDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function getPasswordResetToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasswordResetToken', []);

        return parent::getPasswordResetToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setPasswordResetToken($passwordResetToken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasswordResetToken', [$passwordResetToken]);

        return parent::setPasswordResetToken($passwordResetToken);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasswordResetTokenCreationDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasswordResetTokenCreationDate', []);

        return parent::getPasswordResetTokenCreationDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setPasswordResetTokenCreationDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasswordResetTokenCreationDate', [$date]);

        return parent::setPasswordResetTokenCreationDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateUpdated', []);

        return parent::getDateUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateUpdated', []);

        return parent::setDateUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function getActivationKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivationKey', []);

        return parent::getActivationKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivationKey($activationKey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivationKey', [$activationKey]);

        return parent::setActivationKey($activationKey);
    }

    /**
     * {@inheritDoc}
     */
    public function getNascimento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNascimento', []);

        return parent::getNascimento();
    }

    /**
     * {@inheritDoc}
     */
    public function setNascimento($nascimento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNascimento', [$nascimento]);

        return parent::setNascimento($nascimento);
    }

    /**
     * {@inheritDoc}
     */
    public function getRua()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRua', []);

        return parent::getRua();
    }

    /**
     * {@inheritDoc}
     */
    public function setRua($rua)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRua', [$rua]);

        return parent::setRua($rua);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumero', []);

        return parent::getNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumero($numero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumero', [$numero]);

        return parent::setNumero($numero);
    }

    /**
     * {@inheritDoc}
     */
    public function getBairro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBairro', []);

        return parent::getBairro();
    }

    /**
     * {@inheritDoc}
     */
    public function setBairro($bairro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBairro', [$bairro]);

        return parent::setBairro($bairro);
    }

    /**
     * {@inheritDoc}
     */
    public function getComplemento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComplemento', []);

        return parent::getComplemento();
    }

    /**
     * {@inheritDoc}
     */
    public function setComplemento($complemento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComplemento', [$complemento]);

        return parent::setComplemento($complemento);
    }

    /**
     * {@inheritDoc}
     */
    public function getCidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCidade', []);

        return parent::getCidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setCidade($cidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCidade', [$cidade]);

        return parent::setCidade($cidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', []);

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', [$estado]);

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getCep()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCep', []);

        return parent::getCep();
    }

    /**
     * {@inheritDoc}
     */
    public function setCep($cep)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCep', [$cep]);

        return parent::setCep($cep);
    }

    /**
     * {@inheritDoc}
     */
    public function getCpf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCpf', []);

        return parent::getCpf();
    }

    /**
     * {@inheritDoc}
     */
    public function setCpf($cpf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCpf', [$cpf]);

        return parent::setCpf($cpf);
    }

    /**
     * {@inheritDoc}
     */
    public function getRg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRg', []);

        return parent::getRg();
    }

    /**
     * {@inheritDoc}
     */
    public function setRg($rg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRg', [$rg]);

        return parent::setRg($rg);
    }

    /**
     * {@inheritDoc}
     */
    public function getCelular()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCelular', []);

        return parent::getCelular();
    }

    /**
     * {@inheritDoc}
     */
    public function setCelular($celular)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCelular', [$celular]);

        return parent::setCelular($celular);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefone', []);

        return parent::getTelefone();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefone($telefone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefone', [$telefone]);

        return parent::setTelefone($telefone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPolo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPolo', []);

        return parent::getPolo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPolo($polo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPolo', [$polo]);

        return parent::setPolo($polo);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexo', []);

        return parent::getSexo();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexo($sexo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexo', [$sexo]);

        return parent::setSexo($sexo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPai()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPai', []);

        return parent::getPai();
    }

    /**
     * {@inheritDoc}
     */
    public function setPai($pai)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPai', [$pai]);

        return parent::setPai($pai);
    }

    /**
     * {@inheritDoc}
     */
    public function getMae()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMae', []);

        return parent::getMae();
    }

    /**
     * {@inheritDoc}
     */
    public function setMae($mae)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMae', [$mae]);

        return parent::setMae($mae);
    }

    /**
     * {@inheritDoc}
     */
    public function getNaturalidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNaturalidade', []);

        return parent::getNaturalidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setNaturalidade($naturalidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNaturalidade', [$naturalidade]);

        return parent::setNaturalidade($naturalidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFile', []);

        return parent::getFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setFile($file)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFile', [$file]);

        return parent::setFile($file);
    }

    /**
     * {@inheritDoc}
     */
    public function getCelular2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCelular2', []);

        return parent::getCelular2();
    }

    /**
     * {@inheritDoc}
     */
    public function setCelular2($celular2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCelular2', [$celular2]);

        return parent::setCelular2($celular2);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmissor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmissor', []);

        return parent::getEmissor();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmissor($emissor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmissor', [$emissor]);

        return parent::setEmissor($emissor);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecado', []);

        return parent::getRecado();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecado($recado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecado', [$recado]);

        return parent::setRecado($recado);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormacao', []);

        return parent::getFormacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormacao($formacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormacao', [$formacao]);

        return parent::setFormacao($formacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresa', []);

        return parent::getEmpresa();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpresa($empresa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpresa', [$empresa]);

        return parent::setEmpresa($empresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresaendereco()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresaendereco', []);

        return parent::getEmpresaendereco();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpresaendereco($empresaendereco)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpresaendereco', [$empresaendereco]);

        return parent::setEmpresaendereco($empresaendereco);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresanumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresanumero', []);

        return parent::getEmpresanumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpresanumero($empresanumero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpresanumero', [$empresanumero]);

        return parent::setEmpresanumero($empresanumero);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresacomplemento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresacomplemento', []);

        return parent::getEmpresacomplemento();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpresacomplemento($empresacomplemento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpresacomplemento', [$empresacomplemento]);

        return parent::setEmpresacomplemento($empresacomplemento);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresabairro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresabairro', []);

        return parent::getEmpresabairro();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpresabairro($empresabairro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpresabairro', [$empresabairro]);

        return parent::setEmpresabairro($empresabairro);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresacidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresacidade', []);

        return parent::getEmpresacidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpresacidade($empresacidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpresacidade', [$empresacidade]);

        return parent::setEmpresacidade($empresacidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresacep()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresacep', []);

        return parent::getEmpresacep();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpresacep($empresacep)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpresacep', [$empresacep]);

        return parent::setEmpresacep($empresacep);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresatel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresatel', []);

        return parent::getEmpresatel();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpresatel($empresatel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpresatel', [$empresatel]);

        return parent::setEmpresatel($empresatel);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresaramal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresaramal', []);

        return parent::getEmpresaramal();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpresaramal($empresaramal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpresaramal', [$empresaramal]);

        return parent::setEmpresaramal($empresaramal);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresacel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresacel', []);

        return parent::getEmpresacel();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpresacel($empresacel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpresacel', [$empresacel]);

        return parent::setEmpresacel($empresacel);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebsite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebsite', []);

        return parent::getWebsite();
    }

    /**
     * {@inheritDoc}
     */
    public function setWebsite($website)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebsite', [$website]);

        return parent::setWebsite($website);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresaemail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresaemail', []);

        return parent::getEmpresaemail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpresaemail($empresaemail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpresaemail', [$empresaemail]);

        return parent::setEmpresaemail($empresaemail);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresaestado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresaestado', []);

        return parent::getEmpresaestado();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpresaestado($empresaestado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpresaestado', [$empresaestado]);

        return parent::setEmpresaestado($empresaestado);
    }

    /**
     * {@inheritDoc}
     */
    public function getThumb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getThumb', []);

        return parent::getThumb();
    }

    /**
     * {@inheritDoc}
     */
    public function setThumb($thumb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setThumb', [$thumb]);

        return parent::setThumb($thumb);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getBoleto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoleto', []);

        return parent::getBoleto();
    }

    /**
     * {@inheritDoc}
     */
    public function getCronograma()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCronograma', []);

        return parent::getCronograma();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

}
