<?php
$this->headTitle('Polos');

?>

<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>POLOS DA SOCIEDADE PSICANALÍTICA DO PARANÁ </h3>

                <div class="clearfix"></div>

            </div>

            <div class="title_right">

            </div>
        </div>
        <div class="clearfix"></div>

        <div class="row">



            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">


                    <div class="x_content">




                        <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">

                            <div id="loader" class="loader">   <p style="margin: 10px 0px 0px 15px;">Carregando...</p></div>

                            <thead>
                            <tr>
                                <th>Sigla</th>
                                <th>Cidade</th>
                                <th>Endereço</th>
                                <th>Coordenador</th>
                                <th>Telefone</th>

                            </tr>
                            </thead>
                            <tbody>

                            <?php


                            /** @var \User\Entity\Turma $post */

                            foreach ($this->dados as $post): ?>

                                <tr>
                                    <td><?= $this->escapeHtml($post->getTitulo()); ?></td>
                                    <td><?= $this->escapeHtml($post->getPolo()->getCidade()); ?></td>
                                    <td><?= $this->escapeHtml($post->getEndereco()); ?></td>
                                    <td><?= $this->escapeHtml($post->getCoordenador()); ?></td>

                                    <td><?= $this->escapeHtml($post->getTelefone()); ?></td>
                                </tr>
                            <?php endforeach; ?>

                            </tbody>

                            <tfoot>
                            <tr>
                                <th>Sigla</th>
                                <th>Cidade</th>
                                <th>Endereço</th>
                                <th>Coordenador</th>
                                <th>Telefone</th>

                            </tr>
                            </tfoot>

                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>