 <!-- page content -->
        <div class="right_col" role="main">
          <div class="">
            
            <!--titulo-->
            <div class="page-title">
              <div class="title_left">
                <h3>
                

                </h3>
              </div>

            </div>

<!--end titulo-->
            <div class="clearfix"></div>

            <div class="row">

              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <!--professor-->
                  

                  
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">

                    <div class="text-center text-center">
            <h1 class="error-number">Sem permissão!</h1>
            <h2>Desculpe, você não está autorizado a acessar esta sessão!</h2>
            <p>Entre em contato com o Administrador do polo</p>

        </div>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /page content -->