<!-- page content -->
<div class="right_col" role="main">

    <div class="">
        <div class="page-title">
            <div class="title_left" style="width:100%;">
                <h3>Módulo</h3>

                <div class="row">
                    <div class="col-sm-11">

                    </div>

                    <div class="col-sm-1">

                        <a class="btn btn-primary pull-right" href="javascript:history.back()">
                            <i class="fa fa-reply"></i> Voltar
                        </a>
                    </div>
                </div>
            </div>

        </div>
        <div class="clearfix"></div>

        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="">
                    <div class="x_content">
                        <!--icons-->
                        <div class="row">

                        </div>
                        <!--end icons-->
                        <div class="row">

                            <?php
                            $aula = $this->aula;

                            /**
                             * @var User\Entity\Cronograma  $modulo
                             */
                            foreach ($aula as $resAula => $modulo) {}


                            ?>

                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <div class="x_panel">
                                    <div class="x_title">
                                        <p>Cronograma de Aulas do Módulo: <b><?php echo $modulo->getModulo()->getTitulo(); ?></b>  </p>
                                        <p>Turma: <b><?php echo $modulo->getTurma(); ?></b> </p>


                                        <ul class="nav navbar-right panel_toolbox">
                                            <li>
                                            </li>

                                            <li>
                                            </li>
                                        </ul>
                                        <div class="clearfix"></div>
                                    </div>
                                    <div class="x_content">
                                        <!-- Start to do list -->
                                        <div class="x_content">
                                            <div class="">
                                                <ul class="to_do">

                                                    <?php
                                                    $aula = $this->aula;

                                                    $dataAtual = date("Y-m-d");

                                                    /** @var \User\Entity\Cronograma $resAula */
                                                    foreach ($aula as $resAula) {

                                                        $dataAula = $resAula->getInicio()->format('Y-m-d');

                                                        if(strtotime($dataAtual) >= strtotime($dataAula) ){

                                                            $checkbox = 'checked="checked"';

                                                        }else{
                                                            $checkbox = '';
                                                        }


                                                        ?>
                                                        <li>
                                                            <p>
                                                                <input type="checkbox" <?php echo $checkbox; ?> class="flat"> Dia <?php echo $resAula->getInicio()->format('d/m/Y'); ?> -
                                                                <?php echo $resAula->getAula()->getTitulo(); ?>: <?php echo $resAula->getAula()->getTipo(); ?> - Professor: <?php echo $resAula->getProfessor();?> </p>
                                                        </li>
                                                        <?php

                                                    }
                                                    ?>
                                                    
                                                </ul>
                                            </div>
                                        </div>
                                        <!-- End to do list -->
                                    </div>
                                </div>
                            </div>
                        </div>




                        <br />
                        <div class="row">

                            <?php
                            $aula = $this->aula;

                            $dataAtual = date("Y-m-d");

                            /** @var \User\Entity\Cronograma $listAulas */
                            foreach ($aula as $listAulas){

                            $dataAula = $listAulas->getInicio()->format('Y-m-d');

                            if(strtotime($dataAtual) >= strtotime($dataAula) ) {


                                ?>

                                <div class="col-md-3 col-xs-12 widget widget_tally_box">
                                    <div class="x_panel fixed_height_400">
                                        <div class="x_title" style="height: 60px;">
                                            <h4>  <?php echo $listAulas->getAula(); ?></h4>
                                            <div class="clearfix"></div>
                                        </div>
                                        <div class="x_content">

                                            <!--VIDEO-->
                                            <div class="thumbnail" style="height: auto">
                                                <div class="image view-first">
                                                    <a href="<?php echo $this->url('admin/modulo',
                                                        ['action' => 'aula'],
                                                        ['force_canonical' => true, 'query' =>
                                                            ['code' => $listAulas->getAula()->getCode(), 'turma' => $this->turma ]
                                                        ]); ?>">
                                                    <img class="img-responsive"
                                                         style="width: 100%; display: block;"
                                                         src="<?php echo $this->basePath() . '/img/play.jpg'; ?>"
                                                         alt="image"/>



                                                    </a>
                                                </div>

                                                <p>Acessar Aula</p>

                                            </div>

                                            <!--END VIDEO-->

                                            <!-- Large modal -->



                                            <!--end modal-->


                                            <div class="clearfix"></div>


                                        </div>
                                    </div>
                                </div>


                                <?php
                            }else{}

                            }//end list aulas
                            ?>
                            <div class="clearfix"></div>

                        </div>
                        <div class="row">


            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2>Palavra do Professor</h2>
                  
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <ul class="list-unstyled timeline">

                      <?php
                      $aula = $this->aula;

                      $i = 1;
                      foreach ($aula as $resAula) {

                          $dataAula = $resAula->getInicio()->format('Y-m-d');

                          if(strtotime($dataAtual) >= strtotime($dataAula) ){

                              ?>
                              <li>
                                  <div class="block">
                                      <div class="tags">
                                          <a href="" class="tag">
                                              <span>Aula <?php echo $i; ?></span>
                                          </a>
                                      </div>
                                      <div class="block_content">
                                          <?php

                                          echo $resAula->getAula()->getTexto();
                                          ?>
                                      </div>
                                  </div>
                              </li>

                              <?php
                              $i++;
                          }else{

                          }

                          ?>



                          <?php
                      }

                   ?>


                  </ul>

                </div>
              </div>
            </div>


</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->

