<?php
$this->headTitle('Usuários');

?>

<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Alunos </h3>
            </div>

            <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">

                </div>
            </div>
        </div>
        <div class="clearfix"></div>

        <div class="row">



            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <p>
                            <a class="btn btn-default" href="
    <?= $this->url('admin/default', ['controller' => 'users', 'action'=>'add']); ?>">
                                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Cadastro
                            </a>
                        </p>
                        <div class="clearfix"></div>
                    </div>

                    <p class="text-muted font-13 m-b-30">

                        <?php
                        $flash = $this->flashMessenger();
                        $flash->setMessageOpenFormat('<div%s>
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                                    &times;
                                </button>
                                <ul><li>')
                            ->setMessageSeparatorString('</li><li>')
                            ->setMessageCloseString('</li></ul></div>');

                        echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
                        echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
                        echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
                        echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));

                        ?>

                    </p>
                    <div class="x_content">




                        <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">

                            <div id="loader" class="loader">   <p style="margin: 10px 0px 0px 15px;">Carregando...</p></div>

                            <thead>
                            <tr>
                                <th>Cod</th>
                                <th>Nome</th>
                                <th>E-mail</th>
                                <th>Status</th>
                                <th>Ação</th>

                            </tr>
                            </thead>
                            <tbody>

                            <?php foreach ($alunos as $user): ?>

                                <tr>
                                    <td><?= $this->escapeHtml($user->getId()); ?></td>
                                    <td><?= $this->escapeHtml($user->getFullName()); ?></a>
                                    </td>
                                    <td>
                                        <a href="<?= $this->url('admin/default', ['controller'=> 'users','action'=>'view', 'id'=>$user->getId()]); ?>">
                                            <?= $this->escapeHtml($user->getEmail()); ?>
                                        </a>
                                    </td>
                                    <td><?= $this->escapeHtml($user->getStatusAsString()); ?></td>
                                    <td>

                                        <a class="btn btn-default" href="<?= $this->url('admin/default',
                                            ['controller' => 'users', 'action'=>'change-password', 'id'=>$user->getId()]); ?>">
                                            <span class="glyphicon glyphicon-lock"></span> Senha
                                        </a>
                                  <a class="btn btn-xs btn-primary" href="<?= $this->url('admin/default',
                                            ['controller' => 'users','action'=>'edit', 'id'=>$user->getId()]); ?>"><i class="glyphicon glyphicon-edit"></i></a>

                                        <a class="btn btn-xs btn-danger deletar" href="<?= $this->url('admin/default',
                                            ['controller' => 'users', 'action'=>'delete', 'id'=>$user->getId()]); ?>"><span class="glyphicon glyphicon-floppy-remove"></span></a>

                                    </td>
                                </tr>
                            <?php endforeach; ?>

                            </tbody>

                            <tfoot>
                            <tr>
                                <th>Cod</th>
                                <th>Nome</th>
                                <th>E-mail</th>
                                <th>Status</th>
                                <th>Ação</th>

                            </tr>
                            </tfoot>

                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

