<?php
$this->headTitle('Turma');

?>

<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Minhas Classes </h3>

                <div class="clearfix"></div>



            </div>

            <div class="title_right">

            </div>
        </div>
        <div class="clearfix"></div>

        <div class="row">



            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">

                    <div class="x_content">

                        <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">

                            <div id="loader" class="loader">   <p style="margin: 10px 0px 0px 15px;">Carregando...</p></div>

                            <thead>
                            <tr>
                                <th>Turma</th>
                                <th>Inicio</th>
                                <th>Status</th>
                                <th>Ação</th>

                            </tr>
                            </thead>
                            <tbody>

                            <?php

                            $turma = $this->user;

                            /** @var \User\Entity\Alunos $post */
                            foreach ($turma as $post): ?>

                                <tr>
                                    <td><?= $this->escapeHtml($post->getTurma()->getTitulo()); ?></td>
                                    <td><?= $this->escapeHtml($post->getTurma()->getInicio()->format('d/m/Y')); ?></td>
                                    <td><?= $post->getTurma()->getStatusAsString(); ?></td>
                                    
                                    <td>


                                    </td>
                                </tr>
                            <?php endforeach; ?>

                            </tbody>

                            <tfoot>
                            <tr>
                                <th>Estado</th>
                                <th>Cidade</th>
                                <th>Status</th>
                                <th>Ação</th>

                            </tr>
                            </tfoot>

                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>