<?php
$this->headTitle('Usuários');

$users = $this->users;

?>

<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Usuários </h3>

                <div class="clearfix"></div>
                <p>
                    <a class="btn btn-default" href="
    <?= $this->url('admin/default', ['controller' => 'users', 'action'=>'add']); ?>">
                        <i class="fa fa-plus-circle"></i> Novo
                    </a>

                    <a class="btn btn-default" href="
    <?= $this->url('admin/default', ['controller' => 'users']); ?>">
                        <i class="fa fa-navicon"></i> Listar
                    </a>
                </p>

            </div>

            <div class="title_right">
                <div class="form-group">
                    <?php echo $this->partial('filterTurma');?>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>

        <div class="row">



            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">


                    <p class="text-muted font-13 m-b-30">

                        <?php
                        $flash = $this->flashMessenger();
                        $flash->setMessageOpenFormat('<div%s>
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                                    &times;
                                </button>
                                <ul><li>')
                            ->setMessageSeparatorString('</li><li>')
                            ->setMessageCloseString('</li></ul></div>');

                        echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
                        echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
                        echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
                        echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));

                        ?>

                    </p>
                    <div class="x_content">




                        <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">

                            <div id="loader" class="loader">   <p style="margin: 10px 0px 0px 15px;">Carregando...</p></div>

                            <thead>
                            <tr>

                                <th>Nome</th>
                                <th>Cpf</th>
                                <th>E-mail</th>
                                <th>Acesso</th>
                                <th>Status</th>

                                <th>Ação</th>

                            </tr>
                            </thead>
                            <tbody>

                            <?php

                            /** @var \User\Entity\Alunos $user */
                            foreach ($users as $user): ?>

                                <tr>

                                    <td><?= $this->escapeHtml($user->getUsuario()->getFullName()); ?></a>
                                    </td>

                                    <td><?= $this->escapeHtml($user->getUsuario()->getCpf()); ?></td>
                                    <td>
                                        <a href="<?= $this->url('admin/default', ['controller'=> 'users','action'=>'view', 'id'=>$user->getUsuario()->getId()]); ?>">
                                            <?= $this->escapeHtml($user->getUsuario()->getEmail()); ?>
                                        </a>
                                    </td>



                                    <td><?= $this->escapeHtml($user->getUsuario()->getRole()); ?></td>
                                    <td><?= $this->escapeHtml($user->getUsuario()->getStatusAsString()); ?></td>
                                    <td>

                                        <a class="btn btn-xs btn-primary" href="<?= $this->url('admin/default',
                                            ['controller' => 'users','action'=>'edit', 'id'=>$user->getUsuario()->getId()]); ?>"><i class="glyphicon glyphicon-edit"></i></a>

                                        <a class="btn btn-xs btn-danger deletar" href="<?= $this->url('admin/default',
                                            ['controller' => 'users', 'action'=>'delete', 'id'=>$user->getUsuario()->getId()]); ?>"><span class="glyphicon glyphicon-floppy-remove"></span></a>

                                    </td>
                                </tr>
                            <?php endforeach; ?>

                            </tbody>

                            <tfoot>
                            <tr>

                                <th>Nome</th>
                                <th>Cpf</th>
                                <th>E-mail</th>
                                <th>Acesso</th>
                                <th>Status</th>
                                <th>Ação</th>

                            </tr>
                            </tfoot>

                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

