<?php
$this->headTitle('Recuperar Senha');

$form->get('email')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'E-mail de cadastro'
]);

$form->get('submit')->setAttributes([
    'class'=>'btn btn-large btn-primary',
    'value' => 'Enviar Senha',
]);

$form->prepare();
?>

<div class="">

    <div id="wrapper">
        <div id="login" class=" form">
            <section class="login_content">

                <p class="text-muted font-13 m-b-30">

                    <?php
                    $flash = $this->flashMessenger();
                    $flash->setMessageOpenFormat('<div%s>
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                                    &times;
                                </button>
                                <ul><li>')
                        ->setMessageSeparatorString('</li><li>')
                        ->setMessageCloseString('</li></ul></div>');

                    echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
                    echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
                    echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
                    echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));

                    ?>

                </p>


                <?= $this->form()->openTag($form); ?>
                <h1>Recuperar Senha</h1>
                <p>Digite seu email de cadastro para recuperar sua senha</p>

                <div>
                    <?= $this->formElement($form->get('email')); ?>
                    <?= $this->formElementErrors($form->get('email')); ?>
                </div>
                <div>
                    <?= $this->formElement($form->get('captcha')); ?>
                    <p class="hint">Digite as letras acima.</p>
                </div>

                <div>
                    <?= $this->formElement($form->get('submit')); ?>
                    <?= $this->formElement($form->get('csrf')); ?>
                    <a class="reset_pass" href="<?= $this->url('login') ?>">Logar</a>
                </div>
                <div class="clearfix"></div>
                <div class="separator">

                    <?= $this->form()->closeTag(); ?>

                    <div class="clearfix"></div>
                    <br />
                    <div>
                        <h1><img src="<?php echo $this->basePath('media/').$this->DadosSite()->dados()->getFile(); ?>"></h1>

                        <p>©<?php echo date('Y'); ?> Todos direitos reservados</p>
                    </div>
                </div>
                </form>
            </section>
        </div>


    </div>
</div>