<?php
$this->headTitle('Nova Senha');

$form->get('new_password')->setAttributes(array(
    'class' => 'form-control',
    'placeholder' => 'Digite sua nova Senha'
));
$form->get('confirm_new_password')->setAttributes(array(
    'class' => 'form-control',
    'placeholder' => 'Confirme a nova  Senha'
));
$form->get('submit')->setAttributes(array(
    'class' => 'btn btn-lg btn-primary',
    'id' => 'submit'
))->setValue('Criar nova Senha');
$form->prepare();
?>

<div class="">

    <div id="wrapper">
        <div id="login" class=" form">
            <section class="login_content">


                <?= $this->form()->openTag($form); ?>

                    <h1>Recuperar Senha</h1>

                    <p>Preencha os campos abaixo</p>

                    <div>

                        <?= $this->formElement($form->get('new_password')); ?>
                        <?= $this->formElementErrors($form->get('new_password')); ?>
                    </div>

                    <div>

                        <?= $this->formElement($form->get('confirm_new_password')); ?>
                        <?= $this->formElementErrors($form->get('confirm_new_password')); ?>
                    </div>
                    <div>
                        <?= $this->formElement($form->get('submit')); ?>
                        <a class="reset_pass" href="<?= $this->url('login') ?>">LOGAR</a>
                    </div>

                    <div class="clearfix"></div>
                    <div class="separator">

                        <?= $this->formElement($form->get('csrf')); ?>

                        <div class="clearfix"></div>
                        <br/>
                        <div>
                            <h1><img src="<?php echo $this->basePath('media/').$this->DadosSite()->dados()->getFile(); ?>"></h1>

                            <p>©<?php echo date('Y'); ?> Todos direitos reservados</p>
                        </div>

                        <?= $this->form()->closeTag(); ?>

            </section>
        </div>


    </div>
</div>
