<?php
$this->headTitle('Setup');


$titulo = $form->get('titulo')->setAttributes([
    'class'         =>'form-control',
    'placeholder'   =>'Digite um Título',
])->setLabelAttributes(['class' => 'control-label']);

$email = $form->get('email')->setAttributes([
    'class'         => 'form-control',
    'placeholder'   => 'Email',
])->setLabelAttributes(['class' => 'control-label']);

$telefone = $form->get('fone')->setAttributes([
    'class'         => 'form-control',
    'id'        => 'telefone',
])->setLabelAttributes(['class' => 'control-label']);

$img = $form->get('file')->setAttributes([
    'class'=>'form-control',
])->setLabelAttributes(['class' => 'control-label']);

$status = $form->get('status')->setAttributes([
    'class'         => 'form-control',
    ])->setLabelAttributes(['class' => 'control-label']);

$background = $form->get('background')->setAttributes([
    'class'=>'form-control'
    ])->setLabelAttributes(['class' => 'control-label']);

$contrato = $form->get('contrato')->setAttributes([
    'class'=>'form-control'
])->setLabelAttributes(['class' => 'control-label']);

$host = $form->get('host')->setAttributes([
    'class'=>'form-control'
])->setLabelAttributes(['class' => 'control-label']);

$port = $form->get('port')->setAttributes([
    'class'=>'form-control'
])->setLabelAttributes(['class' => 'control-label']);

$emailhost = $form->get('emailhost')->setAttributes([
    'class'=>'form-control'
])->setLabelAttributes(['class' => 'control-label']);

$passhost = $form->get('passhost')->setAttributes([
    'class'=>'form-control',
    'placeholder'   =>'******',
])->setLabelAttributes(['class' => 'control-label']);

$security = $form->get('security')->setAttributes([
    'class'=>'form-control'
])->setLabelAttributes(['class' => 'control-label']);

$debug = $form->get('debug')->setAttributes([
    'class'=>'form-control'
])->setLabelAttributes(['class' => 'control-label']);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Salvar']);

$form->prepare();
?>


<!-- page content -->
<div class="right_col" role="main">
    <div class="">

        <div class="page-title">
            <div class="title_left">
                <h3>Set Up</h3>
            </div>

        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-9 col-sm-9 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Editar</h2>

                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <?php
                        $flash = $this->flashMessenger();
                        $flash->setMessageOpenFormat('<div%s>
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                                    &times;
                                </button>
                                <ul><li>')
                            ->setMessageSeparatorString('</li><li>')
                            ->setMessageCloseString('</li></ul></div>');

                        echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
                        echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
                        echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
                        echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));

                        ?>




                        <br />
                        <?= $this->form()->openTag($form); ?>


                        <?php $message = $this->formElementErrors($titulo, ['class' => 'help-block']); ?>

                        <div class="form-group<?= $message ? " has-error" : "" ?>">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Titulo <span class="required">*</span>
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">

                                <?= $this->formElement($titulo); ?>
                                <?= $message ?>

                            </div>
                        </div>



                        <?php $message = $this->formElementErrors($email, ['class' => 'help-block']); ?>
                        <div class="form-group<?= $message ? " has-error" : "" ?>">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">E-mail <span class="required">*</span>
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">
                                <?= $this->formElement($email); ?>
                                <?= $message ?>
                            </div>
                        </div>


                      <?php $message = $this->formElementErrors($img, ['class' => 'help-block']); ?>
                        <div class="form-group<?= $message ? " has-error" : "" ?>" style="padding-bottom: 10px;">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Logo
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">
                                <?= $this->formElement($img); ?>
                                <?= $message ?>
                            </div>
                        </div>



                        <?php $message = $this->formElementErrors($background, ['class' => 'help-block']); ?>
                        <div class="form-group<?= $message ? " has-error" : "" ?>" style="padding-bottom: 10px;">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Background
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">
                                <?= $this->formElement($background); ?>
                                <?= $message ?>
                            </div>
                        </div>






                        <div class="ln_solid"></div>

                        <?php $message = $this->formElementErrors($telefone, ['class' => 'help-block']); ?>
                        <div class="form-group<?= $message ? " has-error" : "" ?>">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Telefone
                            </label>
                            <div class="col-md-3 col-sm-3 col-xs-12">
                                <?= $this->formElement($telefone); ?>
                                <?= $message ?>
                            </div>

                        </div>

                        <div class="ln_solid"></div>

                        <?php $message = $this->formElementErrors($host, ['class' => 'help-block']); ?>
                        <div class="form-group<?= $message ? " has-error" : "" ?>">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Host
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">
                                <?= $this->formElement($host); ?>
                                <?= $message ?>
                            </div>
                        </div>

                        <?php $message = $this->formElementErrors($port, ['class' => 'help-block']); ?>
                        <div class="form-group<?= $message ? " has-error" : "" ?>">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Porta
                            </label>
                            <div class="col-md-3 col-sm-3 col-xs-12">
                                <?= $this->formElement($port); ?>
                                <?= $message ?>
                            </div>
                        </div>

                        <?php $message = $this->formElementErrors($emailhost, ['class' => 'help-block']); ?>
                        <div class="form-group<?= $message ? " has-error" : "" ?>">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Usuário
                            </label>
                            <div class="col-md-5 col-sm-5 col-xs-12">
                                <?= $this->formElement($emailhost); ?>
                                <?= $message ?>
                            </div>
                        </div>

                        <?php $message = $this->formElementErrors($passhost, ['class' => 'help-block']); ?>
                        <div class="form-group<?= $message ? " has-error" : "" ?>">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Senha host
                            </label>
                            <div class="col-md-4 col-sm-4 col-xs-12">
                                <?= $this->formElement($passhost); ?>
                                <?= $message ?>
                            </div>
                        </div>

                        <?php $message = $this->formElementErrors($security, ['class' => 'help-block']); ?>
                        <div class="form-group<?= $message ? " has-error" : "" ?>">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Segurança
                            </label>
                            <div class="col-md-2 col-sm-2 col-xs-12">
                                <?= $this->formElement($security); ?>
                                <?= $message ?>
                            </div>
                        </div>

                        <?php $message = $this->formElementErrors($debug, ['class' => 'help-block']); ?>
                        <div class="form-group<?= $message ? " has-error" : "" ?>">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Debug <span class="required">*</span>
                            </label>
                            <div class="col-md-4 col-sm-4 col-xs-12">
                                <?= $this->formElement($debug); ?>
                                <?= $message ?>
                            </div>
                        </div>


                        <div class="ln_solid"></div>


                        <div class="form-group">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12">Status</label>
                            <div class="col-md-2 col-sm-2 col-xs-12">
                                <?= $this->formElement($form->get('status')); ?>
                                <?= $this->formElementErrors($form->get('status')); ?>
                            </div>
                        </div>

                        <hr>
                        <?php $message = $this->formElementErrors($contrato, ['class' => 'help-block']); ?>
                        <div class="form-group<?= $message ? " has-error" : "" ?>" style="padding-bottom: 10px;">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Contrato
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">
                                <?= $this->formElement($contrato); ?>
                                <?= $message ?>
                            </div>
                        </div>


                        <hr>



                    </div>
                </div>
            </div>

            <div class="col-md-3 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Logo</h2>

                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <br />
                        <div class="box-body">



                            <div id="resultImagem">

                                <?php
                                /** @var \User\Entity\Setup $dataBase */
                                $dataBase = $this->dados;

                                if($dataBase->getFile() == null){
                                    ?>
                                    <img width="210" height="137" src="http://placehold.it/210x137" alt="..." class="margin img-responsive" />
                                    <?php
                                }else{
                                    ?>
                                    <img width="100%" src="<?php echo $this->basePath() . '/media/'.$dataBase->getFile(); ?>" alt="..." class="margin img-responsive" />

                                <?php } ?>

                            </div>


                        </div><!-- /.box-body -->
                    </div>
                </div>

                <div class="x_panel">
                    <div class="x_title">
                        <h2>Background</h2>

                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <br />
                        <div class="box-body">



                            <div id="resultImagem">

                                <?php


                                if($dataBase->getBackground() == null){
                                    ?>
                                    <img width="210" height="137" src="http://placehold.it/210x137" alt="..." class="margin img-responsive" />
                                    <?php
                                }else{
                                    ?>
                                    <img width="100%" src="<?php echo $this->basePath() . '/media/'.$dataBase->getBackground(); ?>" alt="..." class="margin img-responsive" />
                                <?php } ?>

                            </div>


                        </div><!-- /.box-body -->
                    </div>
                </div>


                <div class="x_panel">
                    <div class="x_title">
                        <h2>Contrato</h2>

                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <br />
                        <div class="box-body">



                            <div id="resultImagem">



                                    <?php
                                    $contrato = $dataBase->getContrato();
                                    if(empty($contrato)) {
                                    }else {

                                        ?>


                                        <a class="btn btn-primary" style="width: 100%" href="http://<?php echo $_SERVER['HTTP_HOST']; ?>/baixar.php?c=media&f=<?php echo $contrato; ?>">
                                            <i class="fa fa-download"></i> Contrato
                                        </a>

                                        <?php
                                    }
                                    ?>


                            </div>


                        </div><!-- /.box-body -->
                    </div>
                </div>

            </div>



            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">

                    <div class="x_content">


                        <br />

                        <div class="ln_solid"></div>

                        <div class="form-group">


                            <div class="col-md-2 col-sm-2 col-xs-12">

                                <a href="<?php echo $this->url('admin/default', ['controller' => 'home']); ?>"  class="btn btn-danger"><span class="glyphicon glyphicon-remove-sign"></span> Cancelar</a>

                            </div>

                            <div class="col-md-2 col-sm-2 col-xs-12">
                                <?= $this->formElement($form->get('submit')); ?>

                                <?= $this->form()->closeTag(); ?>
                            </div>

                        </div>

                    </div>
                </div>
            </div>

            <?php  echo $this->form()->closeTag(); ?>

        </div>

        <!--img destaque-->

        <!--end img destaque-->




    </div>
</div>
<!-- /page content -->

<!-- Small modal -->

<!--modals -->
<div class="modal fade modalSenha" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="myModalLabel2">Gerar Senha</h4>
            </div>
            <div class="modal-body">
                <h4>Escolha a quantidade de caracteres entre 6 e 9 digitos</h4>
                <div class="res"></div>

                <form class="form-horizontal form-label-left">

                    <div class="form-group">
                        <label class="control-label col-md-3" for="first-name">Qtd. <span class="required">*</span>
                        </label>
                        <div class="col-md-3">
                            <input type="text" id="caracteres" value="6" required="required" class="form-control col-md-3 col-xs-12">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3" for="last-name">Senha <span class="required">*</span>
                        </label>
                        <div class="col-md-6">
                            <input type="text"  value="" class="form-control col-md-6 col-xs-12 resSenha">
                        </div>

                        <div class="col-md-2">
                            <button type="button"  controller="users" class="btn btn-primary gerar">Gerar</button>
                        </div>

                    </div>
                </form>

                <p>Após gerar copie e cole no formulário</p>



            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>

        </div>
    </div>
</div>
<!-- /modals -->


