
        <div class="modal-content">
            <div class="modal-body">
                <div class="x_panel">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                        </button>
                        <h4 class="modal-title" id="myModalLabel">Vídeos</h4>
                    </div>
                    <div class="x_content">
                        <div class="" role="tabpanel" data-example-id="togglable-tabs">
                            <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                                <li role="presentation" class="active"><a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">Listar</a>
                                </li>
                                <li role="presentation" class=""><a href="#tab_content2" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">Cadastrar</a>
                                </li>
                                <li role="presentation" class=""><a  href="#tab_content3" role="tab" id="profile-tab2" data-toggle="tab" aria-expanded="false">Alterar</a>
                                </li>
                            </ul>
                            <div id="myTabContent" class="tab-content">
                                <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">
                                    <div class="resModal">
                                    </div>

                                    <!--listar tabela-->

                                    <div class="resVideos">
                                        <div class="x_content">

                                        <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">


                                        <thead>
                                        <tr>
                                            <th>Cod</th>
                                            <th>Titulo</th>
                                            <th>Tipo</th>
                                           <th>Ativo</th>
                                            <th>Ação</th>


                                        </tr>
                                        </thead>
                                        <tbody>



                                        <?php

                                        $url = $_SERVER['REQUEST_URI'];

                                        $i = explode('/', $url);


                                        foreach($resVideos as $res){
                                   


                                            ?>

                                                                                                                                      
                                            <tr id="row_<?php echo $res->getId(); ?>">

                                                <td><?php echo $res->getId(); ?></td>
                                                <td><?php echo $res->getTitulo(); ?></td>
                                                <td><?php echo $res->getTipo(); ?></td>
                                                <td><?php echo $res->getAtivo(); ?></td>
                                                <td>
                                                    <a class="btn btn-xs btn-primary tab3" href="#tab_content3" role="tab" id="profile-tab2" data-toggle="tab" aria-expanded="false"><i class="glyphicon glyphicon-edit"></i></a>

                                                                                                
                                                <button class="btn btn-xs btn-primary anexar" 
                                                
                                                data-controller="Video"
                                                data-aula="<?php echo  $i['4'];  ?>"
                                                data-anexo = "<?php echo $res->getId(); ?>"
                                            
                                                 href="javascript:void(0);" ><i class="fa fa-share"></i> Anexar</button>

                                                    <a class="btn btn-xs btn-danger deletarModal" id="<?php echo $res->getId(); ?>" href="<?php echo $this->url('admin/default',
                                                        array('controller'=>'video', 'action'=>'delete','id'=>$res->getId()));?>"><span class="glyphicon glyphicon-floppy-remove"></span></a>


                                                </td>
                                            </tr>
                                        <?php } ?>

                                        </tbody>
                                        <tfoot>
                                        <tr>
                                            <th>Cod</th>
                                            <th>Titulo</th>
                                            <th>Tipo</th>
                                            <th>Ativo</th>
                                            <th>Ação</th>


                                        </tr>
                                        </tfoot>

                                    </table>
</div>

                                    </div>




                                    <!--end listar tabela-->
                                </div>

                                <!--cadastrar-->
                                <div role="tabpanel" class="tab-pane fade" id="tab_content2" aria-labelledby="profile-tab">


                                    <div class="row">
                                        <div class="col-md-12 col-sm-12 col-xs-12">
                                            <div class="x_panel">
                                                <div class="x_title">
                                                    <h2>Cadastrar</h2>

                                                    <div class="clearfix"></div>
                                                </div>
                                                <div class="x_content">

                                                    <div class="res">

                                                    </div>

                                                    <div class="progress" style="display: none;">
                                                        <div class="progress-bar" role="progressbar" aria-valuenow="0"
                                                             aria-valuemin="0" aria-valuemax="100" style="width:0%" style="display: none;">
                                                            0%
                                                        </div>
                                                    </div>

                                                    <br />
                                                    <form  name="video" method="post" action="/dashboard/video/new" id="formModal" role="form"  enctype="multipart/form-data" class="form-horizontal form-label-left formModal" >

                                                        <input type="hidden" name="controller" value="video">

                                                        <input type="hidden" name="autor" value="5">

                                                        <div class="form-group">
                                                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Titulo <span class="required">*</span>
                                                            </label>
                                                            <div class="col-md-9 col-sm-9 col-xs-12">
                                                                <input name="titulo" id="stringModal" required="required" class="form-control&#x20;col-md-7&#x20;col-xs-12" placeholder="Digite&#x20;um&#x20;Titulo" type="text" value="">                            </div>
                                                        </div>

                                                        <input type="hidden" name="slug" id="permalinkModal" class="form-control&#x20;col-md-7&#x20;col-xs-12" value="">


                                                        <div class="form-group">
                                                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="last-name">Tipo <span class="required">*</span>
                                                            </label>
                                                            <div class="col-md-5 col-sm-5 col-xs-12">

                                                                <select name="tipo" class="form-control" id="tipoVideo"><option value="YouTube">YouTube</option>
                                                                    <option value="Vimeo">Vimeo</option>
                                                                    <option value="Html5">Html5</option></select>                            </div>
                                                        </div>

                                                        <div class="form-group">
                                                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="last-name">Link <span class="required">*</span>
                                                            </label>
                                                            <div class="col-md-5 col-sm-5 col-xs-12">

                                                                <input type="text" name="link" id="linkVideo" class="form-control&#x20;col-md-7&#x20;col-xs-12" placeholder="Url&#x20;do&#x20;v&#xED;deo" value="">                            </div>
                                                        </div>

                                                        <div class="form-group">
                                                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="last-name">Arquivo
                                                            </label>
                                                            <div class="col-md-9 col-sm-9 col-xs-12">

                                                                <input type="file" name="file" id="fileVideo">                            </div>
                                                        </div>


                                                        <div class="form-group">
                                                            <label class="control-label col-md-2 col-sm-2 col-xs-12">Ativo</label>
                                                            <div class="col-md-2 col-sm-2 col-xs-12">
                                                                <select name="ativo" class="form-control"><option value="Sim">Sim</option>
                                                                    <option value="N&#xE3;o">Nao</option></select>                            </div>
                                                        </div>


                                                </div>
                                            </div>

                                            <div class="x_panel">

                                                <div class="x_content">

                                                    <div class="clearfix"></div>

                                                    <div class="form-group">

                                                        <div class="col-md-10 col-sm-10 col-xs-12">

                                                        </div>


                                                        <div class="col-md-2 col-sm-2 col-xs-12">

                                                            <section class="progress-demo">
                                                                <button type="submit" id="formModal" class="btn btn-primary ladda-button" data-color="white" data-style="expand-right">Salvar</button>
                                                            </section>
                                                        </div>

                                                    </div>

                                                </div>
                                            </div>
                                        </div>

                                        </form>
                                    </div>
                                    

                                </div>

                                <div role="tabpanel" class="tab-pane fade" id="tab_content3" aria-labelledby="profile-tab">
                                    <p>xxFood truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid. Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four loko farm-to-table craft beer twee. Qui photo
                                        booth letterpress, commodo enim craft beer mlkshk </p>
                                </div>

                                

                            </div>
                        </div>









                    </div>
                </div>


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>

            </div>
        </div>
