<?php
$this->headTitle('Alterar Senha');


$old_password = $form->get('old_password')->setAttributes([
    'class'         => 'form-control',
    'placeholder'   =>'Digite a senha antiga'
])->setLabelAttributes(['class' => 'control-label']);


$password = $form->get('new_password')->setAttributes([
    'class'         => 'form-control',
    'placeholder'   =>'Digite a nova senha'
])->setLabelAttributes(['class' => 'control-label']);


$confirm = $form->get('confirm_new_password')->setAttributes([
    'class'         => 'form-control',
    'placeholder'   =>'Confirme a nova senha'
])->setLabelAttributes(['class' => 'control-label']);




$form->get('submit')->setAttributes(['class'=>'btn btn-primary'])->setValue('Salvar');;

$form->prepare();
?>

<!-- page content -->
<div class="right_col" role="main">
    <div class="">

        <div class="page-title">
            <div class="title_left">
                <h3>Usuário</h3>
            </div>

        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-9 col-sm-9 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Alterar Senha para usuário: <?= $this->escapeHtml($user->getEmail()) ?></h2>

                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <?php
                        $flash = $this->flashMessenger();
                        $flash->setMessageOpenFormat('<div%s>
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                                    &times;
                                </button>
                                <ul><li>')
                            ->setMessageSeparatorString('</li><li>')
                            ->setMessageCloseString('</li></ul></div>');

                        echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
                        echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
                        echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
                        echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));

                        ?>

                        <br />
                        <?= $this->form()->openTag($form); ?>


                        <?php $message = $this->formElementErrors($old_password, ['class' => 'help-block']); ?>

                        <div class="form-group<?= $message ? " has-error" : "" ?>">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Senha Antiga <span class="required">*</span>
                            </label>
                            <div class="col-md-5 col-sm-5 col-xs-12">

                                <?= $this->formElement($old_password); ?>
                                <?= $message ?>

                            </div>
                        </div>

                        <div class="clearfix"></div>
                        <br>



                        <?php $message = $this->formElementErrors($password, ['class' => 'help-block']); ?>

                        <div class="form-group<?= $message ? " has-error" : "" ?>">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Nova Senha <span class="required">*</span>
                            </label>
                            <div class="col-md-5 col-sm-5 col-xs-12">

                                <?= $this->formElement($password); ?>
                                <?= $message ?>

                            </div>
                        </div>

                        <div class="clearfix"></div>
                        <br>

                        <?php $message = $this->formElementErrors($confirm, ['class' => 'help-block']); ?>

                        <div class="form-group<?= $message ? " has-error" : "" ?>">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Confirme a Senha <span class="required">*</span>
                            </label>
                            <div class="col-md-5 col-sm-5 col-xs-12">

                                <?= $this->formElement($confirm); ?>
                                <?= $message ?>

                            </div>
                        </div>




                    </div>
                </div>
            </div>

            <div class="col-md-3 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Imagem</h2>

                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <br />
                        <div class="box-body">



                            <div id="resultImagem">

                                <?php

                                $file = $user->getFile();

                                if(empty($file)){
                                    ?>
                                    <img width="210" height="137" src="http://placehold.it/210x137" alt="..." class="margin" />
                                    <?php
                                }else{
                                    ?>
                                    <img width="100%" src="<?php echo $this->basePath() . '/media/'.$user->getFile(); ?>" alt="..." class="margin" />
                                <?php } ?>

                            </div>


                        </div><!-- /.box-body -->
                    </div>
                </div>
            </div>



            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">

                    <div class="x_content">


                        <br />

                        <div class="ln_solid"></div>

                        <div class="form-group">


                            <div class="col-md-2 col-sm-2 col-xs-12">
                                <?= $this->formElement($form->get('csrf')); ?>


                                <?php
                                if($this->UserIdentity()->getDados()->getRole() !== 'Aluno' ) {

                                    ?>
                                    <a href="<?php echo $this->url('admin/default', ['controller' => 'home']) ?>"
                                       class="btn btn-danger"><span class="glyphicon glyphicon-remove-sign"></span>
                                        Cancelar</a>

                                    <?php
                                }else{
                                ?>
                                    <a href="<?php echo $this->url('admin/default', ['controller' => 'alunos', 'action' => 'perfil', 'id' => $this->identity()->getId()]) ?>"
                                       class="btn btn-danger"><span class="glyphicon glyphicon-remove-sign"></span>
                                        Cancelar</a>
                                    <?php
                                }
                                    ?>

                            </div>

                            <div class="col-md-2 col-sm-2 col-xs-12">

                                <?= $this->formElement($form->get('submit')); ?>


                            </div>

                        </div>

                    </div>
                </div>
            </div>

            <?= $this->form()->closeTag(); ?>

        </div>

        <!--img destaque-->

        <!--end img destaque-->




    </div>
</div>



