<?php
$this->headTitle('Recuperar Senha');

$form->get('email')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'E-mail de cadastro'
]);

$form->get('submit')->setAttributes([
    'class'=>'btn btn-lg btn-primary',
    'value' => 'Enviar Senha',
]);

$form->prepare();
?>

<div class="">

    <div id="wrapper">
        <div id="login" class="form">
            <section class="login_content">

                <?= $this->form()->openTag($form); ?>
                <h1>Recuperar Senha</h1>
                <p>Digite seu email de cadastro para recuperar sua senha</p>

                <div>
                    <?= $this->formElement($form->get('email')); ?>
                    <?= $this->formElementErrors($form->get('email')); ?>
                </div>
                <div>


                </div>

                <div>
                    <?= $this->formElement($form->get('submit')); ?>
                    <?= $this->formElement($form->get('csrf')); ?>
                    <a class="reset_pass" href="<?= $this->url('login') ?>">LOGAR</a>
                </div>
                <div class="clearfix"></div>
                <div class="separator">

                    <?= $this->form()->closeTag(); ?>

                    <div class="clearfix"></div>
                    <br />
                    <div>
                        <h1><img src="img/logo_spp_psc.jpg"></h1>

                        <p>©<?php echo date('Y'); ?> Todos direitos reservados</p>
                    </div>
                </div>
                </form>
            </section>
        </div>


    </div>
</div>