<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Recursos </h3>

                <div class="clearfix"></div>
                <p>
                    <a class="btn btn-default" href="
    <?= $this->url('admin/default', ['controller' => 'resources', 'action'=>'new']); ?>">
                        <i class="fa fa-plus-circle"></i> Novo
                    </a>

                    <a class="btn btn-default" href="
    <?= $this->url('admin/default', ['controller' => 'resources']); ?>">
                        <i class="fa fa-navicon"></i> Listar
                    </a>
                </p>
            </div>

            <div class="title_right">

            </div>
        </div>
        <div class="clearfix"></div>

        <div class="row">



            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">


                    <p class="text-muted font-13 m-b-30">

                        <?php
                        $flash = $this->flashMessenger();
                        $flash->setMessageOpenFormat('<div%s>
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                                    &times;
                                </button>
                                <ul><li>')
                            ->setMessageSeparatorString('</li><li>')
                            ->setMessageCloseString('</li></ul></div>');

                        echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
                        echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
                        echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
                        echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));

                        ?>

                    </p>
                    <div class="x_content">




                        <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">

                            <div id="loader" class="loader">   <p style="margin: 10px 0px 0px 15px;">Carregando...</p></div>

                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Titulo</th>

                                <th>Ação</th>

                            </tr>
                            </thead>
                            <tbody>

                            <?php foreach($this->data as $entity): ?>

                                <tr>
                                    <td><?php echo $entity->getId(); ?></td>
                                    <td><?php echo $entity->getNome(); ?></td>

                                    <td><a class="btn btn-xs btn-primary" href="<?php echo $this->url('acl/default',
                                            array('controller'=>'resources','action'=>'edit','id'=>$entity->getId()));?>"><i class="glyphicon glyphicon-edit"></i></a>

                                        <a class="btn btn-xs btn-danger" href="<?php echo $this->url('acl/default',
                                            array('controller'=>'resources','action'=>'delete','id'=>$entity->getId()));?>" onclick="if (confirm('Deseja realmente excluir?')) { document.location = this.href; } return false;"><span class="glyphicon glyphicon-floppy-remove"></span></a>

                                    </td>
                                </tr>
                            <?php endforeach; ?>

                            </tbody>

                            <tfoot>
                            <tr>
                                <th>ID</th>
                                <th>Titulo</th>

                                <th>Ação</th>

                            </tr>
                            </tfoot>

                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>






