<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand page-scroll" href="#">AVA - SPP</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="page-scroll" href="http://www.spp.psc.br/">Ir para o Site</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

<header style="background-image: url('media/<?php echo $this->DadosSite()->dados()->getBackground(); ?>');">
    <div class="header-content">
        <div class="header-content-inner">
            <h1 id="homeHeading"><img src="<?php echo $this->basePath('media/').$this->DadosSite()->dados()->getFile(); ?>"></h1>
            <hr>
            <p>Bem-Vindo ao Ambiente Virtual de Aprendizagem da SPP</p>
            <p>Para acessar é necessário ser cadastrado</p>
            <a href="/login" class="btn btn-primary btn-xl page-scroll">Acessar</a>
            <a href="<?php echo $this->url('register');?>" class="btn btn-primary btn-xl page-scroll">Registrar-se</a>
        </div>
    </div>
</header>


<!-- jQuery -->
<script src="vendor/jquery/jquery.min.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="vendor/bootstrap/js/bootstrap.min.js"></script>

<!-- Plugin JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
<script src="vendor/scrollreveal/scrollreveal.min.js"></script>
<script src="vendor/magnific-popup/jquery.magnific-popup.min.js"></script>

<!-- Theme JavaScript -->
<script src="js/creative.min.js"></script>