<?php
$this->headTitle('Listar Cronograma');

$resTurma = $this->turma;
/**
 * @var  \User\Entity\Turma $turma
 */
foreach($resTurma as $t => $turma){}

?>


<!-- page content -->
<div class="right_col" role="main">

    <div class="">

        <div class="page-title">
            <div class="title_left">
                <h3>Cronograma: <?php echo $turma->getTitulo(); ?> / <?php echo $turma->getPolo()->getCidade(); ?></h3>
<br>
                <div class="clearfix"></div>
                <p>
                    <a class="btn btn-default" href="
    <?= $this->url('admin/default', ['controller' => 'turma']); ?>">
                        <i class="fa fa-navicon"></i> Listar Turma
                    </a>

                    <a class="btn btn-md btn-primary" href="<?php echo $this->url('admin/cronograma', ['controller' => 'cronograma', 'action' => 'new', 'id' => $this->id ]);?>">
                        <i class="fa fa-share"></i> Anexar Aula
                    </a>

                </p>

            </div>

        </div>
        <div class="clearfix"></div>
        <div class="row">

        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Cronograma de Aulas</h2>

                    <div class="clearfix"></div>
                </div>


                <div class="x_content">

                    <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">

                        <thead>
                        <tr>
                            <th>Inicio</th>
                            <th>Módulo</th>
                            <th>Aula</th>
                            <th>Professor</th>

                            <th>Ação</th>

                        </tr>
                        </thead>
                        <tbody>

                        <?php
                        /** @var \User\Entity\Cronograma $cronograma */
                        foreach($this->cron as $cronograma): ?>

                            <tr>
                                <td><?php echo $cronograma->getInicio()->format('d/m/Y'); ?></td>
                                <td><?php if($this->verificaModulo == null){ echo 'Sem Modulo Cadastrado'; }else{echo $cronograma->getModulo();} ?></td>
                                <td><?php if($this->verificaAula == null){echo 'Sem Aula Cadastrada'; }else{ echo $cronograma->getAula();} ?></td>
                                <td><?php echo $cronograma->getProfessor();?></td>

                                <td><a class="btn btn-xs btn-danger deletar"  href="<?php echo $this->url('admin/default', ['controller' => 'cronograma', 'action'=>'delete', 'id'=>$cronograma->getId()]); ?>"><span class="glyphicon glyphicon-floppy-remove"></span></a>

                                </td>
                            </tr>
                        <?php endforeach; ?>

                        </tbody>

                        <tfoot>
                        <tr>
                            <th>Módulo</th>
                            <th>Aula</th>
                            <th>Professor</th>
                            <th>Início</th>

                            <th>Ação</th>

                        </tr>
                        </tfoot>

                    </table>
                </div>
            </div>
        </div>
        </div>
    </div>

    <!--img destaque-->

    <!--end img destaque-->
</div>

<!-- /page content -->





