<?php
$this->headTitle('Cadastrar Cronograma');

$modulo = $form->get('modulo')->setAttributes([
    'class'=>'form-control',
])->setLabelAttributes(['class' => 'control-label']);

$aula = $form->get('aula')->setAttributes([
    'class'=>'form-control',
])->setLabelAttributes(['class' => 'control-label']);


$professor = $form->get('professor')->setAttributes([
    'class'=>'form-control',
])->setLabelAttributes(['class' => 'control-label']);

$inicio = $form->get('inicio')->setAttributes([
    'class'=>'form-control',
    'placeholder' => '99/99/9999',
])->setLabelAttributes(['class' => 'control-label']);


$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => 'Salvar']);

$form->prepare();
?>


<!-- page content -->
<div class="right_col" role="main">
    <div class="">

        <div class="page-title">
            <div class="title_left">
                <h3>Cronograma</h3>

                <div class="clearfix"></div>
                <p>

                    <a class="btn btn-default" href="
    <?= $this->url('admin/cronograma', ['controller' => 'cronograma', 'action'=> 'list', 'id' => $this->id]); ?>">
                        <i class="fa fa-navicon"></i> Listar
                    </a>
                </p>

            </div>

        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-9 col-sm-9 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Cadastrar</h2>

                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <br />
                        <?php

                        $resTurma = $this->turma;
                        foreach ($resTurma as $t => $turma){}


                        $form->setAttribute('action',$this->url('admin/cronograma',array('controller'=>'cronograma','action'=>'new', 'id' => $this->id)));
                        $form->prepare();
                        ?>
                        <?= $this->form()->openTag($form); ?>


                        <div class="form-group">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Turma <span class="required">*</span>
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">
                                <input type="text" readonly class="form-control" value="<?php echo $turma->getTitulo(); ?>">
                            </div>
                        </div>


                        <?php $message = $this->formElementErrors($modulo, ['class' => 'help-block']); ?>

                        <div class="form-group<?= $message ? " has-error" : "" ?>">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Módulo <span class="required">*</span>
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">

                                <?= $this->formElement($modulo); ?>
                                <?= $message ?>

                            </div>
                        </div>

                        <?php $message = $this->formElementErrors($aula, ['class' => 'help-block']); ?>

                        <div class="form-group<?= $message ? " has-error" : "" ?>">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Aula <span class="required">*</span>
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">

                                <?= $this->formElement($aula); ?>
                                <?= $message ?>

                            </div>
                        </div>

                        <?php $message = $this->formElementErrors($professor, ['class' => 'help-block']); ?>

                        <div class="form-group<?= $message ? " has-error" : "" ?>">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Professor <span class="required">*</span>
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">

                                <?= $this->formElement($professor); ?>
                                <?= $message ?>

                            </div>
                        </div>

                        <?php $message = $this->formElementErrors($inicio, ['class' => 'help-block']); ?>
                        <div class="form-group<?= $message ? " has-error" : "" ?>">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Início
                            </label>
                            <div class="col-md-4 col-sm-4 col-xs-12">
                                <?= $this->formElement($inicio); ?>
                                <?= $message ?>
                            </div>
                        </div>


                    </div>
                </div>
            </div>





            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">

                    <div class="x_content">

                        <div class="ln_solid"></div>

                        <div class="form-group">

                            <div class="col-xs-12">

                                <a href="<?php echo $this->url('admin/cronograma', ['controller' => 'cronograma', 'action'=> 'list', 'id' => $this->id]) ?>"  class="btn btn-danger"><span class="glyphicon glyphicon-remove-sign"></span> Cancelar</a>

                                <?= $this->formElement($form->get('submit')); ?>
                            </div>

                        </div>

                    </div>
                </div>
            </div>
        </div>

        <?php  echo $this->form()->closeTag(); ?>

    </div>

    <!--img destaque-->

    <!--end img destaque-->




</div>
</div>
<!-- /page content -->



